server:
  port: 8082

spring:
  application:
    name: privateService
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    service:
      name: privateService
