server:
  port: 9999  #not used

grpc:
    port: 8084

spring:
  application:
    name: grpcServer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    service:
      name: grpcServer
